drone_tags_matrix:
  - id: 0
    name: drone_board_back
    matrix: [1, 0, 0, 0, 0, 1, 0, 0.065, 0, 0, 1, 0, 0, 0, 0, 1]

  - id: 1
    name: drone_board_front
    matrix: [1, 0, 0, 0, 0, 1, 0, -0.065, 0, 0, 1, 0, 0, 0, 0, 1]
