# MPC Planner Configuration
#state_topic: "/xuanwu/eskf/odom"
state_topic: "/xuanwu/uav/baselink/odom"
cmd_topic:   "/xuanwu/uav/nav"

# Control Loop
control_rate: 20.0        # Hz
prediction_horizon: 20    # Steps (N)
lookahead_steps: 1        # Which step to send to JSK controller

# --- Tuning Weights ---
# Position (High penalty = tighter tracking)
Q_pos_x: 100.0
Q_pos_y: 100.0
Q_pos_z: 100.0

# Attitude (Medium penalty)
Q_att_r: 100.0
Q_att_p: 100.0
Q_att_y: 100.0

# Velocity (Low penalty, allows smooth flow)
Q_vel_x: 100.0 
Q_vel_y: 100.0 
Q_vel_z: 100.0 

# Angular Rate (Damping)
Q_omega: 100.0

# Input Usage (Higher = save battery/smoother; Lower = aggressive)
R_thrust: 0.001
