image_width: 1280
image_height: 720
camera_name: usb_cam_forward
camera_matrix:
  rows: 3
  cols: 3
  data: [777.66014,   0.     , 653.13033,
           0.     , 771.63957, 285.4912 ,
           0.     ,   0.     ,   1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.413542, 0.132511, 0.007694, 0.001773, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [552.23199,   0.     , 653.83519,   0.     ,
           0.     , 684.01947, 272.63419,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]
